name: Run tests

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy
          pip install black
      - name: type checking
        run: make typehint
      - name: check code consistency
        run: make black
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: run tests
        run: python -m unittest discover ./tests
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
